language: php

php:
  - 7.0

before_script:
  - mysql -uroot -e "create database amytest"
  - composer install --no-interaction
  - php artisan migrate --force
  - php artisan db:seed --class=TestsSeeder --env=testing

script:
  - vendor/bin/phpunit
